import { io } from "socket.io-client";

// IMPORTANT: Replace this with a valid JWT token generated by your register or login API.
// Using "YOUR_JWT_TOKEN_HERE" will result in an Authentication Error.
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZjNTM2YjY5LThiOTEtNDYzZi1iZTExLTE2OTQ0MTI2NmUxOCIsImVtYWlsIjoib3JnQGV4YW1wbGUuY29tIiwicm9sZSI6Ik9SR0FOSVpFUiIsImlhdCI6MTc4MjkxMDE0NywiZXhwIjoxNzgzNTE0OTQ3fQ.pnwGoZDhTboe6lsZ3TNL8qoFEqtbaSMWTnQvTZt_6M0";

if (!token.startsWith("eyJ")) {
    console.warn("WARNING: The token does not look like a valid JWT (it should start with 'eyJ'). Please make sure you copied it correctly.");
}

console.log("Connecting to Socket.IO server at http://localhost:3000...");

const socket = io("http://localhost:3000", {
    auth: {
        token,
    },
    transports: ["websocket"], // Use WebSocket transport
});

// Handle successful connection
socket.on("connect", () => {
    console.log("✅ Connected successfully! Socket ID:", socket.id);
    console.log("Listening for real-time notifications...");
});

// Handle connection/authentication errors
socket.on("connect_error", (err) => {
    console.error("❌ Connection Error (Authentication Failed):", err.message);
    console.log("👉 Tip: Make sure the backend server is running and you have supplied a valid, active JWT token.");
});

// Handle disconnection
socket.on("disconnect", (reason) => {
    console.log("🔌 Disconnected. Reason:", reason);
});

// Listen to the correct event name emitted by the server ("notification")
socket.on("notification", (data) => {
    console.log("\n🔔 NEW NOTIFICATION RECEIVED:");
    console.log(JSON.stringify(data, null, 2));
});
